# add the following to _config.yml file

title: Sara Kenney
logo: /assets/headshot.png
description: My LinkedIn: (https://www.linkedin.com/in/kenneysara/)
show_downloads: true
theme: jekyll-theme-minimal
